spring:
  application:
    name: AureliaClient
server:
  port: 3001
  error:
    path: /error
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:3000/eureka/}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 5
#security:
#  oauth2:
#    client:
#      client-id: 0oa11ssdbXrCHGG2X4x6
#      client-secret: {cipher}bcc607e7b3eb03cdc856c9654b9d3c4326a06ad4609ab2760aa9f587b753c1bf30c6d84660671a1495041cfc2bfdb19bcbe534bb69d8b1da557753dc2c807da3
#      access-token-uri: https://dev-258781.okta.com/oauth2/default/v1/token
#      user-authorization-uri: https://dev-258781.okta.com/oauth2/default/v1/authorize
#      scope: openid profile email
#      user-info-uri: https://dev-258781.okta.com/oauth2/default/v1/userinfo

