spring:
  application:
    name: AureliaClient
  datasource:
    url: jdbc:mysql://localhost:3306/aurelia_security_db
    username: root
    password: '{cipher}8f6232cd9c33135aec4a0436fda3ac97c7af8abbab5919b3af8c5cfa66f4d2cb'
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 3001
  error:
    path: /error
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:3000/eureka/}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    leaseRenewalIntervalInSeconds: 5
#zuul:
#  routes:
#    AureliaSecurity:
#      path: /auth/**
#      id: AureliaSecurity
#      strip-prefix: false
#      sensitive-headers: Cookie, Set-Cookie

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh
